name: Build and deploy a container to an Azure Container Apps - ACA

env:
  IMAGE_NAME: alexandrotf/backend
  CONTAINERAPPS_APP: album-backend-api
  CONTAINERAPPS_ENVIRONMENT: test-app-env
  RESOURCE_GROUP: Test3

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push-container-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          file: ./backend_api/backend_api_csharp/Dockerfile
          context: ./backend_api/backend_api_csharp

  deploy-to-container-apps:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-push-container-image

    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        registryUrl: ghcr.io
        imageToDeploy: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}
        targetPort: 3500
        ingress: external
        containerAppName: ${{ env.CONTAINERAPPS_APP }}
        containerAppEnvironment: ${{ env.CONTAINERAPPS_ENVIRONMENT }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
